# Generated by Django 5.0.1 on 2024-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0016_alter_department_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('email', models.EmailField(max_length=254, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField(default='null')),
                ('end_date', models.DateField(default='null')),
                ('half_day', models.CharField(max_length=20)),
                ('joining_date', models.DateField(default='null')),
                ('reason', models.CharField(max_length=200)),
                ('status', models.IntegerField(max_length=10)),
            ],
        ),
    ]
