# Generated by Django 5.0.1 on 2024-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0017_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
