# Generated by Django 5.0.1 on 2024-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0018_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='count',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
