# Generated by Django 5.0.1 on 2024-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0023_employee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(),
        ),
    ]
