# Generated by Django 5.0.1 on 2024-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0025_tasks_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
