# Generated by Django 5.0.1 on 2024-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0026_alter_tasks_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out'), ('BREAK_IN', 'Break In'), ('BREAK_OUT', 'Break Out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
