# Generated by Django 5.0.1 on 2024-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0031_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='break_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
