# Generated by Django 5.0.1 on 2024-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0041_alter_employee_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
