# Generated by Django 5.0.1 on 2024-04-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0047_timeentry_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='time_type',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='Break_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='Break_out',
            field=models.TimeField(null=True),
        ),
    ]
