# Generated by Django 5.0.1 on 2024-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0048_remove_timeentry_time_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='clockin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='clockout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
