# Generated by Django 5.0.1 on 2024-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0054_alter_department_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('clockin_time', models.TimeField(blank=True, null=True)),
                ('clockout_time', models.TimeField(blank=True, null=True)),
                ('work_hours', models.TimeField(blank=True, null=True)),
                ('break_time', models.TimeField(default='00:00:00')),
            ],
        ),
    ]
