# Generated by Django 5.0.1 on 2024-04-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0055_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='work_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
