# Generated by Django 5.0.1 on 2024-04-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0059_alter_timeentry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='date',
            new_name='date_field',
        ),
    ]
