# Generated by Django 5.0.1 on 2024-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0002_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=' 0'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.IntegerField(default='0'),
        ),
    ]
