# Generated by Django 5.0.1 on 2024-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0003_alter_employee_age_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=' 0', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
