# Generated by Django 5.0.1 on 2024-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0004_alter_employee_age_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default=' ', upload_to='media/profile_pic'),
        ),
    ]
