# Generated by Django 5.0.1 on 2024-03-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
