# Generated by Django 5.0.1 on 2024-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0011_employee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
