# Generated by Django 5.0.1 on 2024-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0019_leave_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_count',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
