# Generated by Django 5.0.1 on 2024-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0024_alter_employee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
