# Generated by Django 5.0.1 on 2024-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0027_clockevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(auto_now_add=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('break_in_time', models.DateTimeField(blank=True, null=True)),
                ('break_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_work_time', models.IntegerField(default=0)),
                ('total_break_time', models.IntegerField(default=0)),
            ],
        ),
    ]
