# Generated by Django 5.0.1 on 2024-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0033_employee_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_date',
            field=models.DateField(auto_now=True),
        ),
    ]
