# Generated by Django 5.0.1 on 2024-03-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0036_remove_employee_work_date_alter_employee_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
