# Generated by Django 5.0.1 on 2024-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0038_leave_approve_count_leave_deny_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clockin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='clockout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
