# Generated by Django 5.0.1 on 2024-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0046_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
