# Generated by Django 5.0.1 on 2024-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0049_timeentry_clockin_time_timeentry_clockout_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='clockin_time',
            new_name='clockin_time1',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='clockout_time',
            new_name='clockin_time2',
        ),
    ]
