# Generated by Django 5.0.1 on 2024-04-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0056_clock_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
