# Generated by Django 5.0.1 on 2024-04-10 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0058_alter_timeentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
