# Generated by Django 5.0.1 on 2024-03-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0005_employee_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('c', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
                ('e', models.CharField(max_length=200)),
                ('f', models.CharField(max_length=200)),
                ('g', models.CharField(max_length=200)),
                ('h', models.CharField(max_length=200)),
                ('date', models.DateField(default='null')),
            ],
        ),
    ]
