# Generated by Django 5.0.1 on 2024-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0007_tasks_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='i',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
