# Generated by Django 5.0.1 on 2024-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0008_tasks_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
    ]
