# Generated by Django 5.0.1 on 2024-03-22 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0009_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
