# Generated by Django 5.0.1 on 2024-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0013_alter_department_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(),
        ),
    ]
