# Generated by Django 5.0.1 on 2024-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0014_alter_department_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='email',
        ),
        migrations.AddField(
            model_name='tasks',
            name='employee',
            field=models.CharField(default='ad', max_length=100),
            preserve_default=False,
        ),
    ]
