# Generated by Django 5.0.1 on 2024-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0015_remove_tasks_email_tasks_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
