# Generated by Django 5.0.1 on 2024-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0020_leave_leave_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='count',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_count',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
