# Generated by Django 5.0.1 on 2024-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0021_alter_leave_count_alter_leave_leave_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='CME', max_length=200),
            preserve_default=False,
        ),
    ]
