# Generated by Django 5.0.1 on 2024-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0022_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
