# Generated by Django 5.0.1 on 2024-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0028_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='#', upload_to=''),
        ),
    ]
