# Generated by Django 5.0.1 on 2024-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0032_employee_break_time_employee_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.IntegerField(null=True),
        ),
    ]
