# Generated by Django 5.0.1 on 2024-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0034_employee_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
