# Generated by Django 5.0.1 on 2024-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0035_alter_employee_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
