# Generated by Django 5.0.1 on 2024-04-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0037_employee_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approve_count',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='deny_count',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='pending_count',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
