# Generated by Django 5.0.1 on 2024-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0045_employee_work_hours_alter_employee_work_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(choices=[('Break', 'Break'), ('Continue', 'Continue'), ('ClockOut', 'Clock Out')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
