# Generated by Django 5.0.1 on 2024-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0050_rename_clockin_time_timeentry_clockin_time1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
