# Generated by Django 5.0.1 on 2024-04-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0051_leaves_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
