# Generated by Django 5.0.1 on 2024-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0052_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
