# Generated by Django 5.0.1 on 2024-04-10 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave2', '0053_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
